# Generated by Django 6.0.3 on 2026-04-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(help_text='First text for comparison')),
                ('text2', models.TextField(help_text='Second text for comparison')),
                ('comparison_type', models.CharField(choices=[('character', 'Character-by-Character'), ('word', 'Word-by-Word'), ('line', 'Line-by-Line')], default='character', max_length=20)),
                ('similarity_percentage', models.FloatField(default=0)),
                ('differences_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Text Comparison',
                'verbose_name_plural': 'Text Comparisons',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='textcompara_created_e5c573_idx')],
            },
        ),
    ]
