# Generated by Django 6.0.3 on 2026-04-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textcomparator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiFileComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_file_name', models.CharField(help_text='Name of the base file', max_length=255)),
                ('comparison_file_names', models.TextField(help_text='Comma-separated names of files compared against')),
                ('comparison_type', models.CharField(choices=[('character', 'Character-by-Character'), ('word', 'Word-by-Word'), ('line', 'Line-by-Line')], default='character', max_length=20)),
                ('total_files', models.IntegerField(default=2, help_text='Total number of files compared')),
                ('similarity_data', models.JSONField(default=dict, help_text='Dictionary of file names to similarity percentages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Multi-File Comparison',
                'verbose_name_plural': 'Multi-File Comparisons',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='textcompara_created_2adbc0_idx')],
            },
        ),
    ]
