# Generated by Django 6.0.3 on 2026-04-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_speed', models.FloatField(help_text='Download speed in Mbps')),
                ('upload_speed', models.FloatField(help_text='Upload speed in Mbps')),
                ('ping', models.FloatField(help_text='Ping latency in ms')),
                ('grade', models.CharField(choices=[('poor', 'Poor (< 5 Mbps)'), ('fair', 'Fair (5-25 Mbps)'), ('good', 'Good (25-100 Mbps)'), ('excellent', 'Excellent (> 100 Mbps)')], default='fair', max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('isp', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Speed Test Result',
                'verbose_name_plural': 'Speed Test Results',
                'ordering': ['-timestamp'],
            },
        ),
    ]
