# Generated by Django 6.0.3 on 2026-04-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncodingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding_type', models.CharField(choices=[('base64_encode', 'Base64 Encode'), ('base64_decode', 'Base64 Decode'), ('url_encode', 'URL Encode'), ('url_decode', 'URL Decode'), ('html_encode', 'HTML Encode'), ('html_decode', 'HTML Decode'), ('hex_encode', 'Hex Encode'), ('hex_decode', 'Hex Decode')], max_length=50)),
                ('input_data', models.TextField(max_length=5000)),
                ('output_data', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='hashtools_e_created_65f1e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='HashHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('md5', 'MD5'), ('sha1', 'SHA-1'), ('sha256', 'SHA-256'), ('sha512', 'SHA-512'), ('blake2', 'BLAKE2'), ('base64_encode', 'Base64 Encode'), ('base64_decode', 'Base64 Decode'), ('url_encode', 'URL Encode'), ('url_decode', 'URL Decode'), ('html_encode', 'HTML Encode'), ('html_decode', 'HTML Decode'), ('hex_encode', 'Hex Encode'), ('hex_decode', 'Hex Decode')], max_length=50)),
                ('input_data', models.TextField(max_length=5000)),
                ('output_data', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='hashtools_h_created_ec38fb_idx')],
            },
        ),
    ]
