# Generated by Django 6.0.3 on 2026-04-17 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📝', help_text='Emoji icon for category', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
                ('summary', models.TextField(help_text='Brief summary for listings and meta description', max_length=500)),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/featured/')),
                ('meta_title', models.CharField(help_text='Page title (50-60 chars recommended)', max_length=70)),
                ('meta_description', models.CharField(help_text='Meta description (150-160 chars)', max_length=160)),
                ('meta_keywords', models.CharField(help_text='Keywords separated by commas', max_length=200)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=100)),
                ('og_description', models.CharField(blank=True, max_length=160)),
                ('twitter_title', models.CharField(blank=True, max_length=70)),
                ('author', models.CharField(default='GeniusGsm Team', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('read_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('posts', models.ManyToManyField(blank=True, related_name='tags', to='blog.blogpost')),
            ],
            options={
                'verbose_name_plural': 'Blog Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-published_date'], name='blog_blogpo_publish_2a7cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', '-published_date'], name='blog_blogpo_status_793c16_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category', '-published_date'], name='blog_blogpo_categor_cd2625_idx'),
        ),
    ]
