# Generated by Django 6.0.3 on 2026-04-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(choices=[('home', 'Homepage'), ('iplookup', 'IP Lookup'), ('abusecheck', 'Abuse Check'), ('ipbulk', 'IP Bulk'), ('urlanalyzer', 'URL Analyzer'), ('shortener', 'Short Link Expander'), ('preview', 'Link Preview'), ('phishing', 'Phishing Detector'), ('randomlines', 'Random Lines'), ('duplicatecounter', 'Duplicate Counter'), ('jwtchecker', 'JWT Checker'), ('tempmail', 'Temp Mail'), ('speedtest', 'Speed Test')], help_text='Select the application to configure SEO for', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Page title (recommended: 50-60 characters)', max_length=70)),
                ('meta_description', models.CharField(help_text='Meta description for search results (recommended: 150-160 characters)', max_length=160)),
                ('meta_keywords', models.TextField(help_text="Keywords separated by commas (e.g., 'keyword1, keyword2, keyword3')")),
                ('og_title', models.CharField(help_text='Open Graph title for social media sharing', max_length=100)),
                ('og_description', models.CharField(help_text='Open Graph description for social media sharing', max_length=160)),
                ('canonical_url', models.URLField(help_text='Canonical URL for this page')),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter card title (optional)', max_length=70)),
                ('twitter_description', models.CharField(blank=True, help_text='Twitter card description (optional)', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Configuration',
                'verbose_name_plural': 'SEO Configurations',
                'ordering': ['app_name'],
            },
        ),
    ]
