# Generated by Django 6.0.3 on 2026-04-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('weight', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='URLBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_or_domain', models.CharField(max_length=500, unique=True)),
                ('reason', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'URL Blacklists',
            },
        ),
        migrations.CreateModel(
            name='URLAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000)),
                ('expanded_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('domain', models.CharField(max_length=255)),
                ('risk_level', models.CharField(choices=[('safe', 'Safe - آمن'), ('low', 'Low Risk - خطر منخفض'), ('medium', 'Medium Risk - خطر متوسط'), ('high', 'High Risk - خطر عالي'), ('critical', 'Critical Risk - خطر حرج')], default='safe', max_length=20)),
                ('is_phishing', models.BooleanField(default=False)),
                ('phishing_score', models.FloatField(default=0.0)),
                ('phishing_indicators', models.JSONField(blank=True, default=dict)),
                ('has_shortener', models.BooleanField(default=False)),
                ('shortener_service', models.CharField(blank=True, max_length=100)),
                ('domain_age_days', models.IntegerField(blank=True, null=True)),
                ('domain_reputation', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('meta_description', models.TextField(blank=True)),
                ('has_ssl', models.BooleanField(default=False)),
                ('uses_http', models.BooleanField(default=False)),
                ('suspicious_chars', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain'], name='urlanalyzer_domain_a7f1b9_idx'), models.Index(fields=['risk_level'], name='urlanalyzer_risk_le_3d82eb_idx'), models.Index(fields=['-created_at'], name='urlanalyzer_created_50febb_idx')],
            },
        ),
    ]
