# Generated by Django 6.0.3 on 2026-04-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlanalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlanalysisresult',
            name='domain_reputation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='urlanalysisresult',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlanalysisresult',
            name='shortener_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='urlanalysisresult',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
