# Generated by Django 6.0.3 on 2026-04-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlanalyzer', '0002_alter_urlanalysisresult_domain_reputation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlanalysisresult',
            name='risk_level',
            field=models.CharField(choices=[('safe', 'Safe'), ('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='safe', max_length=20),
        ),
    ]
