# Generated by Django 6.0.3 on 2026-04-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhishingDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('domain', models.CharField(max_length=500)),
                ('phishing_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('safe', 'Safe'), ('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical')], default='safe', max_length=20)),
                ('is_phishing', models.BooleanField(default=False)),
                ('suspicious_domain', models.BooleanField(default=False)),
                ('suspicious_ssl', models.BooleanField(default=False)),
                ('suspicious_chars', models.BooleanField(default=False)),
                ('suspicious_url_structure', models.BooleanField(default=False)),
                ('phishing_keywords', models.BooleanField(default=False)),
                ('form_fields', models.IntegerField(default=0)),
                ('redirect_chains', models.IntegerField(default=0)),
                ('indicators_found', models.TextField(blank=True, null=True)),
                ('page_title', models.CharField(blank=True, max_length=500, null=True)),
                ('detection_method', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Phishing Detections',
                'ordering': ['-created_at'],
            },
        ),
    ]
