# Generated by Django 6.0.3 on 2026-04-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubdomainEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('subdomain', models.CharField(max_length=255)),
                ('full_url', models.URLField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active (200)'), ('redirect', 'Redirect (300)'), ('not_found', 'Not Found (404)'), ('forbidden', 'Forbidden (403)'), ('timeout', 'Timeout'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('server_header', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, help_text='Page title from HTML', max_length=255)),
                ('content_length', models.IntegerField(blank=True, null=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('certificate_valid', models.BooleanField(blank=True, null=True)),
                ('certificate_issuer', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subdomain Entry',
                'verbose_name_plural': 'Subdomain Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain', 'created_at'], name='subdomainfi_domain_ddcc9f_idx'), models.Index(fields=['is_active'], name='subdomainfi_is_acti_7a5f87_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubdomainScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('total_subdomains_found', models.IntegerField(default=0)),
                ('active_subdomains', models.IntegerField(default=0)),
                ('scan_date', models.DateField(auto_now_add=True, db_index=True)),
                ('scan_time', models.FloatField(help_text='Scan duration in seconds')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subdomain Scan History',
                'verbose_name_plural': 'Subdomain Scan Histories',
                'ordering': ['-scan_date'],
                'unique_together': {('domain', 'scan_date')},
            },
        ),
    ]
