# Generated by Django 6.0.3 on 2026-04-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenerExpansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2000)),
                ('expanded_url', models.URLField(max_length=2000)),
                ('shortener_service', models.CharField(choices=[('bitly', 'Bit.ly'), ('tinyurl', 'TinyURL'), ('owly', 'Ow.ly'), ('googl', 'Goo.gl'), ('shortlink', 'Short.link'), ('blinkk', 'Bl.ink'), ('rebrantly', 'Rebrand.ly'), ('tinycc', 'Tiny.cc'), ('qrnet', 'QR.net'), ('unknown', 'Unknown Shortener')], default='unknown', max_length=50)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('expansion_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Shortener Expansions',
                'ordering': ['-created_at'],
            },
        ),
    ]
