# Generated by Django 6.0.3 on 2026-04-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000, unique=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('favicon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('domain', models.CharField(blank=True, max_length=500, null=True)),
                ('page_size', models.IntegerField(blank=True, null=True)),
                ('load_time', models.FloatField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('og_data', models.TextField(blank=True, null=True)),
                ('twitter_data', models.TextField(blank=True, null=True)),
                ('dominant_color', models.CharField(blank=True, max_length=7, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Link Previews',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['domain'], name='linkpreview_domain_a12f4e_idx'), models.Index(fields=['-created_at'], name='linkpreview_created_393fbe_idx')],
            },
        ),
    ]
