# Generated by Django 6.0.3 on 2026-04-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNSQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('query_type', models.CharField(choices=[('A', 'A - IPv4'), ('AAAA', 'AAAA - IPv6'), ('MX', 'MX - Mail'), ('NS', 'NS - Nameserver'), ('SOA', 'SOA - Authority'), ('CNAME', 'CNAME - Alias'), ('TXT', 'TXT - Text'), ('PTR', 'PTR - Reverse')], max_length=10)),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='dnstools_dn_created_a18a03_idx')],
            },
        ),
    ]
