# Generated by Django 6.0.3 on 2026-04-07 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=500)),
                ('body_text', models.TextField()),
                ('body_html', models.TextField(blank=True, null=True)),
                ('message_id', models.CharField(editable=False, max_length=500, unique=True)),
                ('in_reply_to', models.CharField(blank=True, max_length=500, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('size_bytes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Temp Email',
                'verbose_name_plural': 'Temp Emails',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='TempMailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Temp Mail Domain',
                'verbose_name_plural': 'Temp Mail Domains',
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(editable=False, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempmail_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.CreateModel(
            name='TempEmailAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.IntegerField()),
                ('data', models.BinaryField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tempmail.tempemail')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
        migrations.CreateModel(
            name='TempInbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('ttl', models.IntegerField(choices=[(3600, '1 hour'), (7200, '2 hours'), (14400, '4 hours'), (86400, '1 day'), (604800, '7 days')], default=3600, help_text='Time to live in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_expired', models.BooleanField(db_index=True, default=False)),
                ('email_count', models.IntegerField(default=0)),
                ('last_email_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('access_token', models.CharField(editable=False, max_length=100, unique=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_inboxes', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempmail.tempmaildomain')),
            ],
            options={
                'verbose_name': 'Temp Inbox',
                'verbose_name_plural': 'Temp Inboxes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tempemail',
            name='inbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='tempmail.tempinbox'),
        ),
        migrations.CreateModel(
            name='UsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_inboxes_created', models.IntegerField(default=0)),
                ('total_emails_received', models.IntegerField(default=0)),
                ('total_api_calls', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tempmail_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Stats',
                'verbose_name_plural': 'Usage Stats',
            },
        ),
        migrations.AddIndex(
            model_name='tempemail',
            index=models.Index(fields=['inbox', '-received_at'], name='tempmail_te_inbox_i_e3377a_idx'),
        ),
        migrations.AddIndex(
            model_name='tempemail',
            index=models.Index(fields=['message_id'], name='tempmail_te_message_c51d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='tempinbox',
            index=models.Index(fields=['email'], name='tempmail_te_email_f36cae_idx'),
        ),
        migrations.AddIndex(
            model_name='tempinbox',
            index=models.Index(fields=['created_at'], name='tempmail_te_created_0ad7b9_idx'),
        ),
        migrations.AddIndex(
            model_name='tempinbox',
            index=models.Index(fields=['expires_at'], name='tempmail_te_expires_7f31be_idx'),
        ),
    ]
