# Generated by Django 6.0.3 on 2026-04-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipbulk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iprange',
            options={'ordering': ['country', 'start_ip']},
        ),
        migrations.AddField(
            model_name='iprange',
            name='country',
            field=models.CharField(choices=[('IQ', '🇮🇶 Iraq'), ('AE', '🇦🇪 UAE'), ('SA', '🇸🇦 Saudi Arabia'), ('EG', '🇪🇬 Egypt'), ('JO', '🇯🇴 Jordan'), ('PS', '🇵🇸 Palestine'), ('LB', '🇱🇧 Lebanon'), ('SY', '🇸🇾 Syria'), ('TN', '🇹🇳 Tunisia'), ('MA', '🇲🇦 Morocco'), ('KW', '🇰🇼 Kuwait'), ('QA', '🇶🇦 Qatar'), ('BH', '🇧🇭 Bahrain'), ('OM', '🇴🇲 Oman'), ('YE', '🇾🇪 Yemen'), ('US', '🇺🇸 United States'), ('GB', '🇬🇧 المملكة المتحدة'), ('CA', '🇨🇦 كندا'), ('AU', '🇦🇺 Australia'), ('JP', '🇯🇵 Japan'), ('DE', '🇩🇪 Germany'), ('FR', '🇫🇷 فرنسا'), ('IN', '🇮🇳 India'), ('CN', '🇨🇳 China'), ('RU', '🇷🇺 Russia'), ('OTHER', '🌍 Other')], default='OTHER', help_text='البلد المرتبط بهذا النطاق', max_length=10),
        ),
        migrations.AddIndex(
            model_name='iprange',
            index=models.Index(fields=['country', 'group'], name='ipbulk_ipra_country_5be45e_idx'),
        ),
    ]
