# Generated by Django 6.0.3 on 2026-04-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipbulk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iprange',
            options={'ordering': ['country', 'start_ip']},
        ),
        migrations.AddField(
            model_name='iprange',
            name='country',
            field=models.CharField(choices=[('IQ', '🇮🇶 العراق'), ('AE', '🇦🇪 الإمارات'), ('SA', '🇸🇦 السعودية'), ('EG', '🇪🇬 مصر'), ('JO', '🇯🇴 الأردن'), ('PS', '🇵🇸 فلسطين'), ('LB', '🇱🇧 لبنان'), ('SY', '🇸🇾 سوريا'), ('TN', '🇹🇳 تونس'), ('MA', '🇲🇦 المغرب'), ('KW', '🇰🇼 الكويت'), ('QA', '🇶🇦 قطر'), ('BH', '🇧🇭 البحرين'), ('OM', '🇴🇲 عمان'), ('YE', '🇾🇪 اليمن'), ('US', '🇺🇸 الولايات المتحدة'), ('GB', '🇬🇧 المملكة المتحدة'), ('CA', '🇨🇦 كندا'), ('AU', '🇦🇺 استراليا'), ('JP', '🇯🇵 اليابان'), ('DE', '🇩🇪 ألمانيا'), ('FR', '🇫🇷 فرنسا'), ('IN', '🇮🇳 الهند'), ('CN', '🇨🇳 الصين'), ('RU', '🇷🇺 روسيا'), ('OTHER', '🌍 أخرى')], default='OTHER', help_text='البلد المرتبط بهذا النطاق', max_length=10),
        ),
        migrations.AddIndex(
            model_name='iprange',
            index=models.Index(fields=['country', 'group'], name='ipbulk_ipra_country_5be45e_idx'),
        ),
    ]
