# Generated by Django 6.0.3 on 2026-04-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipbulk', '0002_alter_iprange_options_iprange_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkimportlog',
            name='errors_log',
            field=models.TextField(blank=True, help_text='Error log'),
        ),
        migrations.AlterField(
            model_name='ipgroup',
            name='description',
            field=models.TextField(blank=True, help_text='Group description'),
        ),
        migrations.AlterField(
            model_name='ipgroup',
            name='name',
            field=models.CharField(help_text='Group name', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='iprange',
            name='country',
            field=models.CharField(choices=[('IQ', '🇮🇶 Iraq'), ('AE', '🇦🇪 United Arab Emirates'), ('SA', '🇸🇦 Saudi Arabia'), ('EG', '🇪🇬 Egypt'), ('JO', '🇯🇴 Jordan'), ('PS', '🇵🇸 Palestine'), ('LB', '🇱🇧 Lebanon'), ('SY', '🇸🇾 Syria'), ('TN', '🇹🇳 Tunisia'), ('MA', '🇲🇦 Morocco'), ('KW', '🇰🇼 Kuwait'), ('QA', '🇶🇦 Qatar'), ('BH', '🇧🇭 Bahrain'), ('OM', '🇴🇲 Oman'), ('YE', '🇾🇪 Yemen'), ('US', '🇺🇸 United States'), ('GB', '🇬🇧 United Kingdom'), ('CA', '🇨🇦 Canada'), ('AU', '🇦🇺 Australia'), ('JP', '🇯🇵 Japan'), ('DE', '🇩🇪 Germany'), ('FR', '🇫🇷 France'), ('IN', '🇮🇳 India'), ('CN', '🇨🇳 China'), ('RU', '🇷🇺 Russia'), ('OTHER', '🌍 Other')], default='OTHER', help_text='Country associated with this range', max_length=10),
        ),
    ]
